modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "CC-BY-4.0"

[[mods]]
modId = "ftbqlocalizations"
version = "${version}"
displayName = "FTBQLocalizations"
displayURL = "https://github.com/LocalizedMC/FTBQLocalizationKeys-Arch"
credits = "BlackAuresArt, TexTrue, LocalizedMC"
authors = "Ameisin"
description = '''
FTBQLocalizations
'''
logoFile = "icon.png"

[[dependencies.ftbqlocalizations]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbqlocalizations]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbqlocalizations]]
modId = "architectury"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbqlocalizations]]
modId = "ftbquests"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
